spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jiyu0116

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:

jwt:
  header: Authorization
  secret: dGhpcyBpcyBteSBoaWRkZW4gand0IHNlY3JldGUga2V5LCB3aGF0IGlzIHlvdXIgand0IHNlY3JldGUga2V5Pw==
  seconds-to-add: 360s

logging:
  level:
    org.springframework.security.web.DefaultSecurityFilterChain: debug
